import { Room } from "../types/room.interface";

export const ROOMS: Room[] = [
  {
    _id: "1",
    name: "Algorithms Deep Dive",
    description: "Sorting & Graph Traversal",
    course: "CS 401",
    ownerId: "10",
    inviteCode: "ABC",
    isPrivate: false,
    capacity: 6,
    members: ["1234", "12345", "567", "9831", "9383"],
    createdAt: new Date(),
  },
  {
    _id: "2",
    name: "Calc III Study Hall",
    description: "Surface Integrals",
    course: "MATH 301",
    ownerId: "11",
    inviteCode: "BCD",
    isPrivate: false,
    capacity: 5,
    members: ["13138"],
    createdAt: new Date(),
  },
  {
    _id: "3",
    name: "Orgo Cram Session",
    description: "Reaction Mechanisms",
    course: "CHEM 110",
    ownerId: "12",
    inviteCode: "CDE",
    isPrivate: true,
    members: ["3131", "39183", "317", "31831"],
    capacity: 4,
    createdAt: new Date(),
  },
  {
    _id: "4",
    name: "Quantum Study Circle",
    description: "Wave Functions",
    course: "PHYS 202",
    ownerId: "13",
    inviteCode: "DEF",
    isPrivate: false,
    members: ["11"],
    capacity: 6,
    createdAt: new Date(),
  },
];
